apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-folio-scratch-mod-calendar
      name: mod-calendar
      namespace: folio-modules
    spec:
      replicas: 1
      selector:
        matchLabels:
          workload.user.cattle.io/workloadselector: apps.deployment-folio-scratch-mod-calendar
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: mod-calendar
            workload.user.cattle.io/workloadselector: apps.deployment-folio-scratch-mod-calendar
          namespace: folio-modules
        spec:
          containers:
            - env:
                - name: JAVA_OPTIONS
                  value: -XX:MaxRAMPercentage=66.0 -Dlog4j2.formatMsgNoLookups=true
              envFrom:
                - configMapRef:
                    name: db-connect
                    optional: true
                - secretRef:
                    name: db-connect
                    optional: true
                - configMapRef:
                    name: folio-modules-global
                    optional: true
              image: folioci/mod-calendar:3.4.0-SNAPSHOT.181
              imagePullPolicy: Always
              imagePullSecrets:
                - name: docker
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /admin/health
                  port: 8081
                  scheme: HTTP
                initialDelaySeconds: 45
                periodSeconds: 60
                successThreshold: 1
                timeoutSeconds: 5
              name: mod-calendar
              ports:
                - containerPort: 8081
                  name: primary
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /admin/health
                  port: 8081
                  scheme: HTTP
                initialDelaySeconds: 45
                periodSeconds: 60
                successThreshold: 1
                timeoutSeconds: 5
              resources:
                limits:
                  cpu: 500m
                  memory: 1Gi
