apiVersion: apps/v1
kind: Deployment
metadata:
  name: mod-configuration
  namespace: folio-modules-test
  labels:
    workload.user.cattle.io/workloadselector: deployment-folio-scratch-mod-configuration
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-folio-scratch-mod-configuration
  strategy:
    type: RollingUpdate
  template:
    metadata:
      namespace: folio-modules-test
      labels:
        app: mod-configuration
        workload.user.cattle.io/workloadselector: deployment-folio-scratch-mod-configuration
    spec:
      containers:
        - name: mod-configuration
          image: folioorg/mod-configuration:5.13.0-SNAPSHOT.139
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 8081
          #     name: 8081_TCP_0
          #     protocol: TCP
          env:
            - name: JAVA_OPTIONS
              value: -XX:MaxRAMPercentage=66.0
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: '5432'
            - name: DB_USERNAME
              value: folio_admin
            - name: DB_PASSWORD
              value: folio_admin
            - name: DB_DATABASE
              value: okapi_modules
            - name: DB_QUERYTIMEOUT
              value: '60000'
            - name: DB_CHARSET
              value: UTF-8
            - name: DB_MAXPOOLSIZE
              value: '5'
          envFrom:
            - configMapRef:
                name: db-connect
                optional: false
            - secretRef:
                name: db-connect
                optional: false
