apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["10.55.148.140"],"port":443,"protocol":"HTTPS","serviceName":"demonstration:web","ingressName":"demonstration:fuseki-temp","hostname":"fuseki-pre.library.tamu.edu","allNodes":true}]
    objectset.rio.cattle.io/applied: >-
      H4sIAAAAAAAA/6xUTW/jNhD9LwP0JjmyLNsxgR6CbLdFkU2N3WQXTdzDiBzbrClSIEe2VcP/vaD8mf247cmY4fjNmzdvtAOs9WfyQTsLArCuw826DwmstFUg4B3VxrUVWYYEKmJUyAhiB2itY2TtbIihK/8lyYG457XrSWQ21NPuRkeQknI5KiaTtMwHmBZjmqeYq1E6VlSOlSxySQXsEzBYkungLgDSE7LzIMA6X6GF5Ie9lhiWIOB2PlblqD8aD2SWFcV4kE8m8zwbjrJy0J+XWXE7KLJhOYEENs6vjEPVawL5K6RTPpAheeiuzkKkiipnA/tu+nRDZeRusSIQEKNDEGqU1P3xqjpWhppknLH2buEphHeEymhLn0g6qwKIUZYl4Kk2WmIA0QVrHTf0hw7sfPugK80g+lkCF4Y7qJDl8uGs4U8bLnKOCVq0Edc7Y7RdPNcKmQ59t58av4jD5sNfok9w+2xxjdpgaU7pfQLc1jH6+AYg5qmqzQnsxx67jMC6osBY1RE7y4s0K9J89NQfi34usv4LJDDXZNTV1LXzHEDA6+tuBtJZRm3JT53nGYjbLJmBsuERK5qBmMU1ptYpqrv3ZAZLF/hYHGtXOhpx1ZQk2fTir7fEFGInH6l5JnXHZ3rDNMuf8lwUQ1EMX66dd2EYuJMAIr/Bn/nDl1DItr+R1TOrfNJi/rl9+LLsv+Qxflz9/d+HXzuuMmW/GQVRpcttdetnsI+adnejnX26SGUbY66P7Kca5Gjqs7IBxOsOdIWdL+xC2y0kh3jaGDN1RssWBNyZDbYBvjqg47Zed29X1W3qq0rv2ElnQMDT/RT2/8RrCa7xkuKQkRrJxmtu751l2nJnLGPcZur1Whta0G9Bojmcp5ijCZSAxBpLbTTrE0p9qlbnIk+o/rKm/egcv9eGQhuYqstzY+/Co7Px+ZjsLklpC4J9Q9H4vtK2a/2BQojaIMdv2I2i9c3Va2rcAr5bf9IxEogV3B7AoxDKhvP7vWkCk3+vfYif8qNJv11DkEtSjSH/eFBZ0Rwbw+k5D99TdP+G2+8eJU3Ja6fOH7VBtt/v9/8HAAD//wb9fwVvBgAA
    objectset.rio.cattle.io/id: be2c6499-b23a-47ef-a2d6-7deb7dc42ce4
  creationTimestamp: '2025-02-06T21:44:14Z'
  generation: 16
  labels:
    cattle.io/creator: norman
    objectset.rio.cattle.io/hash: 8f7db61673c004473299f20560b31fb0483405b9
    workload.user.cattle.io/workloadselector: deployment-demonstration-web
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/publicEndpoints: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:cattle.io/creator: {}
            f:objectset.rio.cattle.io/hash: {}
            f:workload.user.cattle.io/workloadselector: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:cattle.io/timestamp: {}
                f:field.cattle.io/ports: {}
                f:kubectl.kubernetes.io/restartedAt: {}
                f:workload.cattle.io/state: {}
              f:labels:
                .: {}
                f:workload.user.cattle.io/workloadselector: {}
            f:spec:
              f:containers:
                k:{"name":"web"}:
                  .: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":80,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                  f:resources: {}
                  f:securityContext:
                    .: {}
                    f:allowPrivilegeEscalation: {}
                    f:capabilities: {}
                    f:privileged: {}
                    f:readOnlyRootFilesystem: {}
                    f:runAsNonRoot: {}
                  f:stdin: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:tty: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
      manager: agent
      operation: Update
      time: '2025-04-05T01:09:17Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2025-04-05T01:09:17Z'
  name: web
  namespace: james-test-fleet
  resourceVersion: '29228223'
  uid: 1ab0e1ad-dbe8-455f-a14b-0caf53def4fb
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-demonstration-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2024-04-26T17:12:01Z'
        field.cattle.io/ports: >-
          [[{"containerPort":80,"dnsName":"web-nodeport","hostPort":0,"kind":"NodePort","name":"web","protocol":"TCP","sourcePort":0}]]
        kubectl.kubernetes.io/restartedAt: '2024-05-02T22:45:45Z'
        workload.cattle.io/state: '{"c3J2LWs4cy1wcmUtd29ya2VyLWh1Z2Utd2NkYzM=":"c-trw6s:m-hxm8r"}'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-demonstration-web
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: web
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
    - lastTransitionTime: '2025-02-06T21:44:14Z'
      lastUpdateTime: '2025-02-06T21:44:14Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2025-02-06T21:44:14Z'
      lastUpdateTime: '2025-02-06T21:44:14Z'
      message: ReplicaSet "web-6fb7dd7fb5" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 16
