- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      workload.user.cattle.io/workloadselector: deployment-folio-scratch-mod-configuration
    name: mod-configuration
    namespace: folio-modules-test
  spec:
    replicas: 1
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: deployment-folio-scratch-mod-configuration
    updateStrategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: mod-configuration
          workload.user.cattle.io/workloadselector: deployment-folio-scratch-mod-configuration
        namespace: folio-modules-test
      spec:
        containers:
          - env:
              - name: JAVA_OPTIONS
                value: -XX:MaxRAMPercentage=66.0
              - name: DB_HOST
                value: postgres
              - name: DB_PORT
                value: '5432'
              - name: DB_USERNAME
                value: folio_admin
              - name: DB_PASSWORD
                value: folio_admin
              - name: DB_DATABASE
                value: okapi_modules
              - name: DB_QUERYTIMEOUT
                value: '60000'
              - name: DB_CHARSET
                value: UTF-8
              - name: DB_MAXPOOLSIZE
                value: '5'
            envFrom:
              value:
                configMapRef:
                  name: db-connect
                  optional: false
                secretRef:
                  name: db-connect
                  optional: false
            image: folioorg/mod-configuration:5.13.0-SNAPSHOT.139
            imagePullPolicy: Always
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /admin/health
                port: '8081'
                scheme: HTTP
              initialDelaySeconds: 45
              periodSeconds: 60
              successThreshold: 1
              timeoutSeconds: 5
            name: mod-configuration
            ports:
              - containerPort: 8081
                name: 8081_TCP_0
                protocol: TCP
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /admin/health
                port: '8081'
                scheme: HTTP
              initialDelaySeconds: 45
              periodSeconds: 60
              successThreshold: 1
              timeoutSeconds: 5
            resources:
              limits:
                cpu: 500m
                memory: 1Gi
