apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      workload.user.cattle.io/workloadselector: deployment-folio-scratch-mod-configuration
    name: mod-configuration
    namespace: folio-modules-test
  spec:
    replicas: 1
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: deployment-folio-scratch-mod-configuration
    strategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: mod-configuration
          workload.user.cattle.io/workloadselector: deployment-folio-scratch-mod-configuration
        namespace: folio-modules-test
      spec:
        containers:
          - image: folioorg/mod-configuration:5.13.0-SNAPSHOT.139
            imagePullPolicy: Always
            name: mod-configuration
