apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx5
  namespace: james-test-fleet
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-james-test-fleet-nginx5
  serviceName: 'nginx5-test'
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-james-test-fleet-nginx5
      namespace: james-test-fleet
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx5
