apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  namespace: folio-modules-test
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-folio-modules-test-nginx2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-folio-modules-test-nginx2
      namespace: folio-modules-test
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx2
